#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thyrsus.Character
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Character")]
	public partial class characterDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public characterDataContext() : 
				base(global::Thyrsus.Character.Properties.Settings.Default.CharacterConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public characterDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public characterDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public characterDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public characterDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetCharInfo")]
		public ISingleResult<GetCharInfoResult> GetCharInfo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AID", DbType="Int")] System.Nullable<int> aID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aID);
			return ((ISingleResult<GetCharInfoResult>)(result.ReturnValue));
		}
	}
	
	public partial class GetCharInfoResult
	{
		
		private int _GID;
		
		private string _CharName;
		
		private short _job;
		
		private short _clevel;
		
		private short _sppoint;
		
		private int _exp;
		
		private short _jobpoint;
		
		private byte _STR;
		
		private byte _AGI;
		
		private byte _VIT;
		
		private byte _INT;
		
		private byte _DEX;
		
		private byte _LUK;
		
		private int _hp;
		
		private int _maxhp;
		
		private short _sp;
		
		private short _maxsp;
		
		private int _AID;
		
		private string _mapname;
		
		private short _xPos;
		
		private short _yPos;
		
		private int _GuildID;
		
		private byte _CharNum;
		
		private short _speed;
		
		private int _money;
		
		private int _jobexp;
		
		private int _virtue;
		
		private int _honor;
		
		private byte _haircolor;
		
		private int _joblevel;
		
		private int _bodystate;
		
		private int _healthstate;
		
		private short _sxPos;
		
		private short _syPos;
		
		private string _restartMapName;
		
		private int _effectstate;
		
		private short _head;
		
		private short _weapon;
		
		private short _accessory;
		
		private short _headpalette;
		
		private short _bodypalette;
		
		private short _accessory2;
		
		private short _accessory3;
		
		private short _shield;
		
		private short _party_config;
		
		private short _equipwinopen;
		
		private short _font;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Data.Linq.Binary _checksum;
		
		private System.DateTime _delrevdate;
		
		private bool _bIsChangedCharName;
		
		private int _robepalette;
		
		private System.Nullable<int> _chr_slot_change;
		
		private System.Nullable<int> _chr_name_changeCNT;
		
		public GetCharInfoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GID", DbType="Int NOT NULL")]
		public int GID
		{
			get
			{
				return this._GID;
			}
			set
			{
				if ((this._GID != value))
				{
					this._GID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CharName", DbType="VarChar(24) NOT NULL", CanBeNull=false)]
		public string CharName
		{
			get
			{
				return this._CharName;
			}
			set
			{
				if ((this._CharName != value))
				{
					this._CharName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job", DbType="SmallInt NOT NULL")]
		public short job
		{
			get
			{
				return this._job;
			}
			set
			{
				if ((this._job != value))
				{
					this._job = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clevel", DbType="SmallInt NOT NULL")]
		public short clevel
		{
			get
			{
				return this._clevel;
			}
			set
			{
				if ((this._clevel != value))
				{
					this._clevel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sppoint", DbType="SmallInt NOT NULL")]
		public short sppoint
		{
			get
			{
				return this._sppoint;
			}
			set
			{
				if ((this._sppoint != value))
				{
					this._sppoint = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exp", DbType="Int NOT NULL")]
		public int exp
		{
			get
			{
				return this._exp;
			}
			set
			{
				if ((this._exp != value))
				{
					this._exp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobpoint", DbType="SmallInt NOT NULL")]
		public short jobpoint
		{
			get
			{
				return this._jobpoint;
			}
			set
			{
				if ((this._jobpoint != value))
				{
					this._jobpoint = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STR", DbType="TinyInt NOT NULL")]
		public byte STR
		{
			get
			{
				return this._STR;
			}
			set
			{
				if ((this._STR != value))
				{
					this._STR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AGI", DbType="TinyInt NOT NULL")]
		public byte AGI
		{
			get
			{
				return this._AGI;
			}
			set
			{
				if ((this._AGI != value))
				{
					this._AGI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VIT", DbType="TinyInt NOT NULL")]
		public byte VIT
		{
			get
			{
				return this._VIT;
			}
			set
			{
				if ((this._VIT != value))
				{
					this._VIT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INT", DbType="TinyInt NOT NULL")]
		public byte INT
		{
			get
			{
				return this._INT;
			}
			set
			{
				if ((this._INT != value))
				{
					this._INT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEX", DbType="TinyInt NOT NULL")]
		public byte DEX
		{
			get
			{
				return this._DEX;
			}
			set
			{
				if ((this._DEX != value))
				{
					this._DEX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUK", DbType="TinyInt NOT NULL")]
		public byte LUK
		{
			get
			{
				return this._LUK;
			}
			set
			{
				if ((this._LUK != value))
				{
					this._LUK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hp", DbType="Int NOT NULL")]
		public int hp
		{
			get
			{
				return this._hp;
			}
			set
			{
				if ((this._hp != value))
				{
					this._hp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxhp", DbType="Int NOT NULL")]
		public int maxhp
		{
			get
			{
				return this._maxhp;
			}
			set
			{
				if ((this._maxhp != value))
				{
					this._maxhp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sp", DbType="SmallInt NOT NULL")]
		public short sp
		{
			get
			{
				return this._sp;
			}
			set
			{
				if ((this._sp != value))
				{
					this._sp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxsp", DbType="SmallInt NOT NULL")]
		public short maxsp
		{
			get
			{
				return this._maxsp;
			}
			set
			{
				if ((this._maxsp != value))
				{
					this._maxsp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AID", DbType="Int NOT NULL")]
		public int AID
		{
			get
			{
				return this._AID;
			}
			set
			{
				if ((this._AID != value))
				{
					this._AID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mapname", DbType="VarChar(24) NOT NULL", CanBeNull=false)]
		public string mapname
		{
			get
			{
				return this._mapname;
			}
			set
			{
				if ((this._mapname != value))
				{
					this._mapname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xPos", DbType="SmallInt NOT NULL")]
		public short xPos
		{
			get
			{
				return this._xPos;
			}
			set
			{
				if ((this._xPos != value))
				{
					this._xPos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yPos", DbType="SmallInt NOT NULL")]
		public short yPos
		{
			get
			{
				return this._yPos;
			}
			set
			{
				if ((this._yPos != value))
				{
					this._yPos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuildID", DbType="Int NOT NULL")]
		public int GuildID
		{
			get
			{
				return this._GuildID;
			}
			set
			{
				if ((this._GuildID != value))
				{
					this._GuildID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CharNum", DbType="TinyInt NOT NULL")]
		public byte CharNum
		{
			get
			{
				return this._CharNum;
			}
			set
			{
				if ((this._CharNum != value))
				{
					this._CharNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_speed", DbType="SmallInt NOT NULL")]
		public short speed
		{
			get
			{
				return this._speed;
			}
			set
			{
				if ((this._speed != value))
				{
					this._speed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_money", DbType="Int NOT NULL")]
		public int money
		{
			get
			{
				return this._money;
			}
			set
			{
				if ((this._money != value))
				{
					this._money = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobexp", DbType="Int NOT NULL")]
		public int jobexp
		{
			get
			{
				return this._jobexp;
			}
			set
			{
				if ((this._jobexp != value))
				{
					this._jobexp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_virtue", DbType="Int NOT NULL")]
		public int virtue
		{
			get
			{
				return this._virtue;
			}
			set
			{
				if ((this._virtue != value))
				{
					this._virtue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_honor", DbType="Int NOT NULL")]
		public int honor
		{
			get
			{
				return this._honor;
			}
			set
			{
				if ((this._honor != value))
				{
					this._honor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_haircolor", DbType="TinyInt NOT NULL")]
		public byte haircolor
		{
			get
			{
				return this._haircolor;
			}
			set
			{
				if ((this._haircolor != value))
				{
					this._haircolor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_joblevel", DbType="Int NOT NULL")]
		public int joblevel
		{
			get
			{
				return this._joblevel;
			}
			set
			{
				if ((this._joblevel != value))
				{
					this._joblevel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bodystate", DbType="Int NOT NULL")]
		public int bodystate
		{
			get
			{
				return this._bodystate;
			}
			set
			{
				if ((this._bodystate != value))
				{
					this._bodystate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_healthstate", DbType="Int NOT NULL")]
		public int healthstate
		{
			get
			{
				return this._healthstate;
			}
			set
			{
				if ((this._healthstate != value))
				{
					this._healthstate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sxPos", DbType="SmallInt NOT NULL")]
		public short sxPos
		{
			get
			{
				return this._sxPos;
			}
			set
			{
				if ((this._sxPos != value))
				{
					this._sxPos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_syPos", DbType="SmallInt NOT NULL")]
		public short syPos
		{
			get
			{
				return this._syPos;
			}
			set
			{
				if ((this._syPos != value))
				{
					this._syPos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_restartMapName", DbType="VarChar(24) NOT NULL", CanBeNull=false)]
		public string restartMapName
		{
			get
			{
				return this._restartMapName;
			}
			set
			{
				if ((this._restartMapName != value))
				{
					this._restartMapName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_effectstate", DbType="Int NOT NULL")]
		public int effectstate
		{
			get
			{
				return this._effectstate;
			}
			set
			{
				if ((this._effectstate != value))
				{
					this._effectstate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_head", DbType="SmallInt NOT NULL")]
		public short head
		{
			get
			{
				return this._head;
			}
			set
			{
				if ((this._head != value))
				{
					this._head = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weapon", DbType="SmallInt NOT NULL")]
		public short weapon
		{
			get
			{
				return this._weapon;
			}
			set
			{
				if ((this._weapon != value))
				{
					this._weapon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accessory", DbType="SmallInt NOT NULL")]
		public short accessory
		{
			get
			{
				return this._accessory;
			}
			set
			{
				if ((this._accessory != value))
				{
					this._accessory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_headpalette", DbType="SmallInt NOT NULL")]
		public short headpalette
		{
			get
			{
				return this._headpalette;
			}
			set
			{
				if ((this._headpalette != value))
				{
					this._headpalette = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bodypalette", DbType="SmallInt NOT NULL")]
		public short bodypalette
		{
			get
			{
				return this._bodypalette;
			}
			set
			{
				if ((this._bodypalette != value))
				{
					this._bodypalette = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accessory2", DbType="SmallInt NOT NULL")]
		public short accessory2
		{
			get
			{
				return this._accessory2;
			}
			set
			{
				if ((this._accessory2 != value))
				{
					this._accessory2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accessory3", DbType="SmallInt NOT NULL")]
		public short accessory3
		{
			get
			{
				return this._accessory3;
			}
			set
			{
				if ((this._accessory3 != value))
				{
					this._accessory3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shield", DbType="SmallInt NOT NULL")]
		public short shield
		{
			get
			{
				return this._shield;
			}
			set
			{
				if ((this._shield != value))
				{
					this._shield = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_party_config", DbType="SmallInt NOT NULL")]
		public short party_config
		{
			get
			{
				return this._party_config;
			}
			set
			{
				if ((this._party_config != value))
				{
					this._party_config = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_equipwinopen", DbType="SmallInt NOT NULL")]
		public short equipwinopen
		{
			get
			{
				return this._equipwinopen;
			}
			set
			{
				if ((this._equipwinopen != value))
				{
					this._equipwinopen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_font", DbType="SmallInt NOT NULL")]
		public short font
		{
			get
			{
				return this._font;
			}
			set
			{
				if ((this._font != value))
				{
					this._font = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checksum", DbType="VarBinary(4)")]
		public System.Data.Linq.Binary checksum
		{
			get
			{
				return this._checksum;
			}
			set
			{
				if ((this._checksum != value))
				{
					this._checksum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delrevdate", DbType="DateTime NOT NULL")]
		public System.DateTime delrevdate
		{
			get
			{
				return this._delrevdate;
			}
			set
			{
				if ((this._delrevdate != value))
				{
					this._delrevdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bIsChangedCharName", DbType="Bit NOT NULL")]
		public bool bIsChangedCharName
		{
			get
			{
				return this._bIsChangedCharName;
			}
			set
			{
				if ((this._bIsChangedCharName != value))
				{
					this._bIsChangedCharName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_robepalette", DbType="Int NOT NULL")]
		public int robepalette
		{
			get
			{
				return this._robepalette;
			}
			set
			{
				if ((this._robepalette != value))
				{
					this._robepalette = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chr_slot_change", DbType="Int")]
		public System.Nullable<int> chr_slot_change
		{
			get
			{
				return this._chr_slot_change;
			}
			set
			{
				if ((this._chr_slot_change != value))
				{
					this._chr_slot_change = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chr_name_changeCNT", DbType="Int")]
		public System.Nullable<int> chr_name_changeCNT
		{
			get
			{
				return this._chr_name_changeCNT;
			}
			set
			{
				if ((this._chr_name_changeCNT != value))
				{
					this._chr_name_changeCNT = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
